spring:
  datasource:
    jta:
      company:
        name: company-main
        driver-class-name: com.mysql.cj.jdbc.MysqlXADataSource
        url: jdbc:mysql://13.125.83.74:3326/company?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        username: root
        password: tbxldtmxk123@
        slaves:
          slave1:
            name: company-slave1
            driver-class-name: com.mysql.cj.jdbc.MysqlXADataSource
            url: jdbc:mysql://13.125.83.74:3327/company?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
            username: root
            password: tbxldtmxk123@
      store:
        name: store-main
        driver-class-name: com.mysql.cj.jdbc.MysqlXADataSource
        url: jdbc:mysql://13.125.83.74:3336/store?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        username: root
        password: tbxldtmxk123@
        slaves:
          slave1:
            name: store-slave1
            driver-class-name: com.mysql.cj.jdbc.MysqlXADataSource
            url: jdbc:mysql://13.125.83.74:3337/store?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
            username: root
            password: tbxldtmxk123@
      contract:
        name: contract-main
        driver-class-name: com.mysql.cj.jdbc.MysqlXADataSource
        url: jdbc:mysql://13.125.83.74:3316/contract?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        username: root
        password: tbxldtmxk123@
        slaves:
          slave1:
            name: contract-slave1
            driver-class-name: com.mysql.cj.jdbc.MysqlXADataSource
            url: jdbc:mysql://13.125.83.74:3317/contract?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
            username: root
            password: tbxldtmxk123@
      payment:
        name: payment-main
        driver-class-name: com.mysql.cj.jdbc.MysqlXADataSource
        url: jdbc:mysql://13.125.83.74:3346/payment?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        username: root
        password: tbxldtmxk123@
        slaves:
          slave1:
            name: payment-slave1
            driver-class-name: com.mysql.cj.jdbc.MysqlXADataSource
            url: jdbc:mysql://13.125.83.74:3347/payment?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
            username: root
            password: tbxldtmxk123@
      admin:
        name: admin-main
        driver-class-name: com.mysql.cj.jdbc.MysqlXADataSource
        url: jdbc:mysql://13.125.83.74:3356/admin?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        username: root
        password: tbxldtmxk123@
        slaves:
          slave1:
            name: admin-slave1
            driver-class-name: com.mysql.cj.jdbc.MysqlXADataSource
            url: jdbc:mysql://13.125.83.74:3357/admin?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
            username: root
            password: tbxldtmxk123@
  servlet:
    multipart:
      location: C:\\Temp\\upload\\
      maxFileSize: 100MB
      maxRequestSize: 100MB

e201:
  security:
    auth:
      filter:
        auth-path:
          method: "POST"
          company-path: "/companies/auth"
          manager-path: "/companies/managers/auth"
          employee-path: "/companies/employees/auth"
          store-path: "/stores/auth"
        creation-path:
          method: "POST"
          company-info-path: "/companies/info"
          company-path: "/companies"
          manager-path: "/companies/managers"
          employee-path: "/companies/employees"
          store-path: "/stores"
          license-path: "/ocr/license"
          fin-path: "/fin/create"
  ocr:
    url: https://wjc5ib2j72.apigw.ntruss.com/custom/v1/34604/212ebc463e99de964408b10bdece423efa8af91ea95653cf55ecd221e2a30d88/document/biz-license
    key: cElxWk9jZHhBU0xGdmVwdlZKTUpPUnZ0SnVManF2Q3A=
  fin:
    baseUrl: https://finopenapi.ssafy.io/ssafy/api/v1/edu/
    apiKey: aaa5b6acd90240e899ff1dd8b635a224
    userKey: 6f4e1f99-8cdc-48b6-a06a-5f544ad3106e
    accountTypeNo: 999-1-16011f4698f24d
---

spring:
  config:
    activate:
      on-profile: local
  test: local1

---

spring:
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      location: /tmp/upload
      maxFileSize: 100MB
      maxRequestSize: 100MB
  test: prod1

---

spring:
  config:
    activate:
      on-profile: test
  test: test1